@startuml
package commands {
    package main{
        package product{
            class ProductCommand{
                --Private Data--
                -productService : ProductService
                -subCommands : List<Command>
                --Constructor--
                +ProductCommand(productService : ProductService)
                --Public Methods--
                +initSubCommands() : void
                +apply(args : String[]) : boolean
            }

            class ProductAddCommand{
                --Private Data--
                -productService : ProductService
                --Constructor--
                +ProductAddCommand(productService : ProductService)
                --Public Methods--
                +apply(args : String[]) : boolean

            }

            class ProductAddFoodCommand{
                --Private Data--
                -productService : ProductService
                --Constructor--
                +ProductAddFoodCommand(productService : ProductService)
                --Public Methods--
                +apply(args : String[]) : boolean
            }

            class ProductAddMeetingCommand{
                --Private Data--
                -productService : ProductService
                --Constructor--
                +ProductAddMeetingCommand(productService : ProductService)
                --Public Methods--
                +apply(args : String[]) : boolean
            }

            class ProductListCommand{
                --Private Data--
                -productService : ProductService
                --Constructor--
                +ProductListCommand(productService : ProductService)
                --Public Methods--
                +apply(args : String[]) : boolean
            }

            class ProductRemoveCommand{
                --Private Data--
                -productService : ProductService
                --Constructor--
                +ProductRemoveCommand(productService : ProductService)
                --Public Methods--
                +apply(args : String[]) : boolean
            }

            class ProductUpdateCommand{
                --Private Data--
                -productService : ProductService
                --Constructor--
                +ProductUpdateCommand(productService : ProductService)
                --Public Methods--
                +apply(args : String[]) : boolean
            }
        }

        package ticket{
            class TicketCommand{
                --Private Data--
                -productService : ProductService
                -ticketService : TicketService
                -subCommands : List<Command>
                --Constructor--
                +TicketCommand(ticketService : TicketService, productService : ProductService)
                --Public Methods--
                +initSubCommands() : void
                +apply(args : String[]) : boolean
            }

            class TicketAddCommand{
                --Private Data--
                -ticketService : TicketService
                -productService : ProductService
                --Constructor--
                +TicketAddCommand(ticketService : TicketService, productService : ProductService)
                --Public Methods--
                +apply(args : String[]) : boolean
            }

            class TicketListCommand{
                --Private Data--
                -ticketService : TicketService
                --Constructor--
                +TicketListCommand(ticketService : TicketService)
                --Public Methods--
                +apply(args : String[]) : boolean
            }

            class TicketNewCommand{
                --Private Data--
                -ticketService : TicketService
                -userService : UserService
                --Constructor--
                +TicketNewCommand(ticketService : TicketService, userService : UserService)
                --Public Methods--
                +apply(args : String[]) : boolean
            }

            class TicketPrintCommand{
                --Private Data--
                -ticketService : TicketService
                -userService : UserService
                --Constructor--
                +TicketPrintCommand(ticketService : TicketService, userService : UserService)
                --Public Methods--
                +apply(args : String[]) : boolean
            }

            class TicketRemoveCommand{
                --Private Data--
                -ticketService : TicketService
                -userService : UserService
                --Constructor--
                +TicketRemoveCommand(ticketService : TicketService, userService : UserService)
                --Public Methods--
                +apply(args : String[]) : boolean
            }
        }

        package user{
            class UserCommand{
                 --Private Data--
                 -userService : UserService
                 -subCommands : List<Command>
                 --Constructor--
                 +UserCommand(userService : UserService)
                 --Public Methods--
                 +initSubCommands() : void
                 +apply(args : String[]) : boolean
            }

            package cash{
                class CashCommand{
                    --Private Data--
                    -userService : UserService
                    -subCommands : List<Command>
                    --Constructor--
                    +CashCommand(userService : UserService)
                    --Public Methods--
                    +initSubCommands() : void
                    +apply(args : String[]) : boolean
                }

                class CashAddCommand{
                    --Private Data--
                    -userService : UserService
                    --Constructor--
                    +CashAddCommand(userService : UserService)
                    --Public Methods--
                    +apply(args : String[]) : boolean
                }

                class CashListCommand{
                    --Private Data--
                    -userService : UserService
                    --Constructor--
                    +CashListCommand(userService : UserService)
                    --Public Methods--
                    +apply(args : String[]) : boolean
                }

                class CashRemoveCommand{
                    --Private Data--
                    -userService : UserService
                    --Constructor--
                    +CashRemoveCommand(userService : UserService)
                    --Public Methods--
                    +apply(args : String[]) : boolean
                }

                class CashTicketsCommand{
                    --Private Data--
                    -userService : UserService
                    --Constructor--
                    +CashTicketsCommand(userService : UserService)
                    --Public Methods--
                    +apply(args : String[]) : boolean
                }

            }

            package client{
                class ClientCommand{
                    --Private Data--
                    -userService : UserService
                    -subCommands : List<Command>
                    --Constructor--
                    +ClientCommand(userService : UserService)
                    --Public Methods--
                    +initSubCommands() : void
                    +apply(args : String[]) : boolean
                }

                class ClientAddCommand{
                    --Private Data--
                    -userService : UserService
                    --Constructor--
                    +ClientAddCommand(userService : UserService)
                    --Public Methods--
                    +apply(args : String[]) : boolean
                }

                class ClientListCommand{
                    --Private Data--
                    -userService : UserService
                    --Constructor--
                    +ClientListCommand(userService : UserService)
                    --Public Methods--
                    +apply(args : String[]) : boolean
                }

                class ClientRemoveCommand{
                    --Private Data--
                    -userService : UserService
                    --Constructor--
                    +ClientRemoveCommand(userService : UserService)
                    --Public Methods--
                    +apply(args : String[]) : boolean
                }
            }
        }
        class HelpCommand {
            --Public Methods--
            +HelpCommand()
            +apply(args : String[]) : boolean
            +getHelp() : String
        }

        class UnknownCommand{
            --Public Methods--
            +UnknownCommand()
        }
    }
    abstract class Command {
        --Protected Methods--
        #Command(name : String)
        --Public Methods--
        +apply(args : String[]) : boolean
    }
}


set separator none
package etsisi.upm.es {
    class CLI implements IController {
        --Private / Protected / Static Data--
        -PROMPT : String {final}
        -{static} s : Scanner
        --Constructor--
        +CLI()
        --Public / Static Methods--
        +start(commandHandler : CommandHandler, args : String[]) : void
        +{static}printMessage(message : String) : void
        +{static}printError(errorMessage : String) : void
        +{static}readCommand() : String
        +{static}printPrompt(prompt : String) : void
        +{static}printIfIsFileInput(command : String) : void
        --Protected Methods--
        #echo(message : String) : void
        --Private Methods--
        -mainLoop(commandHandler : CommandHandler) : void
        -printIfIsNotNull(message : String) : void
    }

    class CommandHandler {
        --Private Data--
        -productService : ProductService
        -ticketService : TicketService
        -userService : UserService
        -commands : List<Command>
        --Protected / Private Methods--
        #init() : String
        -initCommands() : void
        #applyCommand(commandUni : String[]) : Command
        #end() : String
    }

    interface IController {
        +start(commandHandler: CommandHandler, args: String[]) : void
    }

    class Shop{
        --Public / Static Methods--
        {static}main(args : String[]) : void
    }
}


package exceptionHandler{
    class ErrorMessageHandler{
    --Private Data--
    -{static}ERRORMESAGE : String[]
    -{static}VALIDNUMBER : String[]
    -{static}VALIDCATEGORY : String[]
    -{static}WRONGID : String[]
    -{static}NOTFINDGID : String[]
    -{static}NOSPACERICKET : String[]
    -{static}PRODUCTNOTEXIST : String[]
    -{static}IDNOTEXIST : String[]
    -{static}FIELDERROR : String[]
    -{static}NOMOREPRODUCTS : String[]
    -{static}EXISTINGID : String[]
    -{static}EXISTINGIDCASH : String[]
    -{static}WRONGCASHID : String[]
    -{static}WRONGDNIFORMAT : String[]
    -{static}DNINOTEXIST : String[]
    -{static}CASHIDNOTEXIST : String[]
    -{static}USE_CLOSED_TICKET : String[]
    -{static}TICKET_ALREADY_EXISTS : String[]
    -{static}TICKET_DOESN'T_EXIST : String[]
    }
}


package model{
    package products{
        class BaseProduct extends Product implements ICategorizable{
            --Private Data--
            -category : Category
            --Constructor--
            +BaseProduct(id : int, name : String, category : Category, price : float)

        }

        class CustomProduct extends BaseProduct{
            --Private Data--
            -maxPers : int
            --Constructor--
            +CustomProduct(id : int, name : String, price : float, maxPeople : int)

        }

        class EventProduct extends Product{
            --Private Data--
            -date : LocalDate
            -maxPeople : int
            --Constructor--
            +EventProduct(id : int, name : String, price : float, date : LocalDate, maxPeople : int)

        }

        class Food extends EventProduct{
            --Constructor--
            +Food(id : int, name : String, price : float, date : LocalDate, maxPeople : int)

        }

        class Meeting extends EventProduct{
            --Constructor--
            +Meeting(id : int, name : String, price : float, date : LocalDate, maxPeople : int)

        }

        class Product implements IProduct{
            --Private Data--
            -id : int
            -name : String
            -price : float
            -maxPersons : int
            --Constructor--
            +Product(id : int, name : String, category : Category, price : float, maxPersons : int)

        }

        class ProductService{
            --Private Data--
            -products : HashMap<Integer, IProduct>
            -MAX_QUANTITY : int
            --Constructor--
            +ProductService()
            --Public Methods--
            +prodAdd(name : String, category : Category, price : float) : String
            +prodAdd(id : int, name : String, category : Category, price : float) : String
            +prodAdd(name : String, category : Category, price : float, maxPers : price) : String
            +prodAdd(id : int, name : String, category : Category, price : float, maxPers : price) : String
            +prodAddFood(name : String, price : float, date : LocalDate, maxPeople : int) : String
            +prodAddFood(id : int, name : String, price : float, date : LocalDate, maxPeople : int) : String
            +prodAddMeeting(name : String, price : float, date : LocalDate, maxPeople : int) : String
            +prodAddMeeting(id : int, name : String, price : float, date : LocalDate, maxPeople : int) : String
            +prodUpdate(id : int, field : String, value : String) : String
            +prodList() : String
            +prodRemove(id : int) : String

        }

        enum Category{
            MERCH
            STATIONERY
            CLOTHES
            BOOK
            ELECTRONICS

        }

        interface ICategorizable{

        }

        interface IProduct{

        }
    }


    package tickets{
        class Ticket{
            --Private / Static Data--
            -{static} closing : DateTimeFormatter
            -id : String
            -{static} MAX_AMOUNT : int
            -ticketItems : IProduct[]
            -numProducts : int
            -status : TicketStatus
            --Constructor--
            +Ticket(id : String)
            --Public Methods--
            +newTicket() : void
            +addProductToTicket(id : int, amount : int, productService : ProductService) : String
            +ticketRemove(id : int) : void
            +printTicket() : String
        }

        class TicketService{
            --Private / Static Data--
            -{static}opening : DateTimeFormatter
            --Public Methods--
            +ticketNew(cashID : String, clientID : String, userService : UserService) : String
            +ticketNew(ticketID : String, cashID : String, clientID : String, userService : UserService) : String
            +ticketAdd(ticketID : String, cashID : String, productID : int, amount : int, userService : UserService, productService : ProductService) : String
            +ticketAdd(ticketID : String, cashID : String, productID : int, amount : int, personalizableTexts : String[], userService : UserService, productService : ProductService) : String
            +ticketList(userService : UserService) : String
            +ticketRemove(ticketID : String, cashID : String, userService : UserService) : String
            +ticketPrint(ticketID : String, cashID : String, userService : UserService) : String
        }

        enum TicketStatus{
        EMPTY
        ACTIVE
        CLOSED
        }
    }


    package users{
        class Cash extends User{
            --Constructor--
            +Cash(id : String, name : String, email : String)
            --Public Methods--
            +deleteTicket(cashID : String, user : HashMap<String, IUser>)
        }

        class Client extends User{
            --Private Data--
            -cashID : String
            --Constructor--
            +Client(id : String, name : String, email : String, cashID : String)
        }

        class User implements IUser{
            --Private Data--
            -id : String
            -name : String
            -email : String
            tickets : HashMap<String, Ticket>
            --Constructor--
            +User(id : String, name : String, email : String)
            --Public Methods--
            +newTicket (ticketID : String, ticket : Ticket) : String
            +addProductToTicket(ticketID : String, productID : int, amount : int, productService : ProductService) : String
            +removeTicket(ticketID : String) : String
        }

        class UserService{
            --Private Data--
            -users : HashMap<String, IUser>
            -numClients : int
            -numCashs : int
            --Constructor--
            +UserService()
            --Public Methods--
            +clientAdd(name : String, dni : String, email : String, cashID : String) : String
            +clientRemove(dni : String) : String
            +clientList() : String
            +cashAdd(name : String, email : String) : String
            +cashAdd(cashID : String, name : String, email : String) : String
            +cashRemove(cashID : String) : String
            +cashList() : String
            +cashTickets(cashID : String) : String
        }

        interface IUser{

        }
    }
}
' CommandHandler
UserCommand --> CommandHandler : uses
ProductCommand --> CommandHandler : uses
TicketCommand --> CommandHandler : uses
HelpCommand --> CommandHandler : uses
UnknownCommand --> CommandHandler : uses
ProductService --> CommandHandler : uses
UserService --> CommandHandler : uses
TicketService --> CommandHandler : uses

' Product commands
ProductAddCommand --> ProductCommand : uses
ProductAddFoodCommand --> ProductCommand : uses
ProductAddMeetingCommand --> ProductCommand : uses
ProductListCommand --> ProductCommand : uses
ProductRemoveCommand --> ProductCommand : uses
ProductUpdateCommand --> ProductCommand : uses

' Ticket commands
TicketAddCommand --> TicketCommand : uses
TicketListCommand --> TicketCommand : uses
TicketNewCommand --> TicketCommand : uses
TicketPrintCommand --> TicketCommand : uses
TicketRemoveCommand --> TicketCommand : uses

' User commands
CashCommand --> UserCommand  : uses
CashAddCommand --> CashCommand : uses
CashListCommand --> CashCommand : uses
CashRemoveCommand --> CashCommand : uses
CashTicketsCommand --> CashCommand : uses
ClientCommand --> UserCommand  : uses
ClientAddCommand --> ClientCommand : uses
ClientListCommand --> ClientCommand : uses
ClientRemoveCommand --> ClientCommand : uses

' CLI
CommandHandler --> CLI : uses
CLI --> Shop : uses

' Uses
ProductService --> IProduct : uses
TicketService --> Ticket : uses
UserService --> IUser : uses

' Notes
note top of Command
    All Command classes extend from this class
end note
note top of ErrorMessageHandler
    Many classes use errors from this class
end note

' Cardinalidades

' Ordenacion

@enduml